### ISSUE TITLE
I get the same error every time

### ISSUE THREAD

**Issue by tocacyy** [AvalerionHF/PancakeSwap-Prediction-v2#4]
Started Epoch 22074
Now waiting for 4.691666666666666 min

Getting Amounts
Bull Amount 7.030856810631030778 BNB
Bear Amount 1.873259721845497077 BNB

Betting on Bear Bet.
Bear Betting Tx Started.
Bear Betting Tx Error

**Comment by AvalerionHF** [comment]
Minimum bet amount can not be less than 0.002 BNB ($2 at the time of writing this). Also make sure you have enough balance in you Binance Smart Chain wallet. `Bear Betting Tx Error` means there was an error signing the transaction. 

Please paste your wallet address here so I can verify it for you.

**Comment by AvalerionHF** [comment]
I have made changes which will now display warning if your balance is low: https://github.com/AvalerionHF/PancakeSwap-Prediction-v2/commit/907b48b96ac1c25e238edc162ae11ee6a5e17609
